In [113]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\student\anaconda3\lib\site-packages (0.22.1)
Requirement already satisfied: scipy>=0.17.0 in c:\users\student\anaconda3\lib\site-packages (from scikit-learn) (1.4.1)
Requirement already satisfied: joblib>=0.11 in c:\users\student\anaconda3\lib\site-packages (from scikit-learn) (0.14.1)
Requirement already satisfied: numpy>=1.11.0 in c:\users\student\anaconda3\lib\site-packages (from scikit-learn) (1.18.1)

In [143]:
import sklearn
import pandas as pd
import numpy as np
import seaborn as sns
import math

import matplotlib.pyplot as plt
import csv

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

import keras
from keras.layers import Dense, Concatenate, Input, Lambda
from keras.models import Model

In [115]:
#for tra data
df = pd.read_csv(r"C:\Users\Student\Downloads\optdigits_69_N200.tra")

In [116]:
df

,0,0.1,5,14,4,0.2,0.3,0.4,0.5,0.6,...,0.27,0.28,0.29,4.6,12.1,14.4,7,0.30,0.31,6.1
0,0,0,0,10,12,0,0,0,0,0,...,0,0,0,1,11,14,12,1,0,6
1,0,0,2,14,10,0,0,0,0,1,...,0,0,0,1,12,14,12,4,0,6
2,0,0,2,13,5,0,0,0,0,0,...,0,0,0,4,15,12,9,1,0,6
3,0,0,2,13,6,0,0,0,0,0,...,0,0,0,2,12,14,12,4,0,6
4,0,0,1,12,11,0,0,0,0,0,...,2,0,0,2,14,15,12,3,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0,0,0,8,13,10,5,0,0,0,...,0,0,0,0,14,15,2,0,0,9
195,0,0,0,3,10,13,12,4,0,0,...,0,0,0,0,1,15,1,0,0,9
196,0,0,0,4,10,13,12,0,0,0,...,0,0,0,0,2,11,0,0,0,9
197,0,0,6,14,16,9,0,0,0,5,...,0,0,0,8,14,16,13,1,0,9
198,0,0,2,13,16,7,0,0,0,0,...,0,0,0,2,12,16,16,4,0,9

In [117]:
df.shape

(199, 65)

In [118]:
df.dtypes

0       int64
0.1     int64
5       int64
14      int64
4       int64
        ...
14.4    int64
7       int64
0.30    int64
0.31    int64
6.1     int64
Length: 65, dtype: object

In [119]:
#Calculating mean and variance
for column in df:
    print("Mean: " + str(np.mean(df[column])) + "And Variance: "+ str(np.var(df[column])))

Mean: 0.0And Variance: 0.0
Mean: 0.05025125628140704And Variance: 0.057776318779828736
Mean: 2.959798994974874And Variance: 12.70190146713467
Mean: 10.673366834170855And Variance: 17.83803439307088
Mean: 9.834170854271356And Variance: 21.243857478346506
Mean: 3.4623115577889445And Variance: 25.44455948082118
Mean: 1.2311557788944723And Variance: 11.926466503371142
Mean: 0.06532663316582915And Variance: 0.22186308426554804
Mean: 0.0And Variance: 0.0
Mean: 1.0753768844221105And Variance: 4.672710285093818
Mean: 9.693467336683417And Variance: 24.483927173556207
Mean: 12.547738693467336And Variance: 14.800484836241514
Mean: 8.78391959798995And Variance: 29.395520315143553
Mean: 5.71356783919598And Variance: 35.22951440620184
Mean: 1.899497487437186And Variance: 18.462261054013833
Mean: 0.1658291457286432And Variance: 0.8820484331203737
Mean: 0.0And Variance: 0.0
Mean: 2.291457286432161And Variance: 9.03063053963284
Mean: 12.844221105527637And Variance: 11.307391227494241
Mean: 7.864321608040201And Variance: 32.58963157496025
Mean: 4.653266331658291And Variance: 32.75917274816291
Mean: 6.9296482412060305And Variance: 50.628216459180365
Mean: 2.0552763819095476And Variance: 14.615034973864287
Mean: 0.035175879396984924And Variance: 0.1042902956996036
Mean: 0.0And Variance: 0.0
Mean: 2.407035175879397And Variance: 8.110704275144592
Mean: 12.613065326633166And Variance: 19.091487588697255
Mean: 9.055276381909549And Variance: 28.072321406025143
Mean: 7.517587939698492And Variance: 37.857730865382145
Mean: 7.869346733668341And Variance: 52.17388449786625
Mean: 2.0452261306532664And Variance: 8.736648064442823
Mean: 0.0And Variance: 0.0
Mean: 0.0And Variance: 0.0
Mean: 1.7537688442211055And Variance: 7.070023484255409
Mean: 9.140703517587939And Variance: 43.81939850003787
Mean: 9.00502512562814And Variance: 34.718567712936505
Mean: 9.422110552763819And Variance: 29.319310118431382
Mean: 11.668341708542714And Variance: 20.191510315396094
Mean: 3.28643216080402And Variance: 10.304891290623974
Mean: 0.0And Variance: 0.0
Mean: 0.0And Variance: 0.0
Mean: 0.9296482412060302And Variance: 2.5980657054114706
Mean: 7.673366834170854And Variance: 55.47622534784473
Mean: 5.773869346733668And Variance: 38.77801065629642
Mean: 5.417085427135678And Variance: 33.730562359536414
Mean: 10.321608040201005And Variance: 21.052347162950483
Mean: 7.28140703517588And Variance: 24.785131688593726
Mean: 0.08542713567839195And Variance: 0.29923486780636693
Mean: 0.0And Variance: 0.0
Mean: 0.2864321608040201And Variance: 1.0586601348450786
Mean: 7.160804020100502And Variance: 28.35605161485817
Mean: 9.155778894472363And Variance: 28.88528067473045
Mean: 6.849246231155779And Variance: 27.293856215752125
Mean: 9.668341708542714And Variance: 24.442766596803125
Mean: 8.326633165829145And Variance: 35.546577106638686
Mean: 0.47738693467336685And Variance: 1.9680816141006698
Mean: 0.0And Variance: 0.0
Mean: 0.04522613065326633And Variance: 0.04318072775940006
Mean: 3.150753768844221And Variance: 12.720991894144085
Mean: 10.673366834170855And Variance: 19.1747178101563
Mean: 13.517587939698492And Variance: 11.17431377995503
Mean: 10.517587939698492And Variance: 30.651700714628426
Mean: 4.055276381909548And Variance: 20.755738491452266
Mean: 0.1708542713567839And Variance: 0.7145274109239662
Mean: 7.507537688442211And Variance: 2.249943183252948

In [120]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
194    False
195    False
196    False
197    False
198    False
Length: 199, dtype: bool

In [121]:
#for tes data
df1 = pd.read_csv(r"C:\Users\Student\Downloads\optdigits_69.tes")
df1

,0,0.1,0.2,12,13,0.3,0.4,0.5,0.6,0.7,...,0.31,0.32,0.33,1,9,15.2,11.1,3.2,0.34,6
0,0,0,0,8,15,1,0,0,0,0,...,2,0,0,0,7,15,16,11,0,6
1,0,0,1,13,14,3,0,0,0,0,...,0,0,0,3,12,15,14,7,0,6
2,0,0,0,5,14,2,0,0,0,0,...,0,0,0,0,5,16,15,3,0,6
3,0,0,0,10,13,1,0,0,0,1,...,0,0,0,0,7,15,15,5,0,6
4,0,0,0,9,10,0,0,0,0,0,...,0,0,0,0,6,12,14,9,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,0,0,7,16,9,8,2,0,0,5,...,0,0,0,7,15,14,7,0,0,9
356,0,0,5,14,11,8,0,0,0,4,...,0,0,0,7,15,12,5,0,0,9
357,0,0,4,14,15,6,0,0,0,5,...,0,0,0,4,13,15,9,0,0,9
358,0,0,4,10,13,6,0,0,0,1,...,0,0,0,2,14,15,9,0,0,9
359,0,0,2,10,7,0,0,0,0,0,...,0,0,0,5,12,16,12,0,0,9

In [127]:
#Calculating mean and variance
for column in df1:
    print("Mean: " + str(np.mean(df1[column])) + " And Variance: "+ str(np.var(df1[column])))

Mean: 0.0 And Variance: 0.0
Mean: 0.07222222222222222 And Variance: 0.11145061728395075
Mean: 3.4138888888888888 And Variance: 14.648140432098785
Mean: 11.497222222222222 And Variance: 14.08332561728391
Mean: 10.411111111111111 And Variance: 21.13654320987653
Mean: 3.7 And Variance: 22.326666666666654
Mean: 0.7916666666666666 And Variance: 7.742708333333338
Mean: 0.06111111111111111 And Variance: 0.6518209876543207
Mean: 0.0 And Variance: 0.0
Mean: 1.2333333333333334 And Variance: 5.4233333333333436
Mean: 9.908333333333333 And Variance: 24.07215277777777
Mean: 12.05 And Variance: 17.13638888888888
Mean: 8.161111111111111 And Variance: 24.04626543209877
Mean: 6.122222222222222 And Variance: 39.068395061728424
Mean: 1.3277777777777777 And Variance: 11.770339506172878
Mean: 0.06111111111111111 And Variance: 0.3684876543209873
Mean: 0.0 And Variance: 0.0
Mean: 2.202777777777778 And Variance: 9.367214506172845
Mean: 12.511111111111111 And Variance: 13.755432098765414
Mean: 7.569444444444445 And Variance: 31.11739969135802
Mean: 4.6194444444444445 And Variance: 27.19684413580244
Mean: 7.108333333333333 And Variance: 53.041041666666715
Mean: 1.6083333333333334 And Variance: 9.199375
Mean: 0.022222222222222223 And Variance: 0.05506172839506163
Mean: 0.0 And Variance: 0.0
Mean: 2.1416666666666666 And Variance: 5.682708333333345
Mean: 12.055555555555555 And Variance: 19.402469135802452
Mean: 10.136111111111111 And Variance: 27.01758487654322
Mean: 8.566666666666666 And Variance: 39.17888888888893
Mean: 8.05 And Variance: 47.51416666666651
Mean: 1.988888888888889 And Variance: 8.355432098765428
Mean: 0.0 And Variance: 0.0
Mean: 0.0 And Variance: 0.0
Mean: 1.8833333333333333 And Variance: 7.314166666666607
Mean: 8.841666666666667 And Variance: 46.2499305555554
Mean: 9.025 And Variance: 36.10770833333331
Mean: 8.577777777777778 And Variance: 35.56061728395053
Mean: 11.01388888888889 And Variance: 19.90258487654321
Mean: 3.841666666666667 And Variance: 12.088819444444475
Mean: 0.0 And Variance: 0.0
Mean: 0.0 And Variance: 0.0
Mean: 1.0472222222222223 And Variance: 2.972770061728389
Mean: 7.608333333333333 And Variance: 53.36048611111128
Mean: 5.65 And Variance: 38.644166666666926
Mean: 4.002777777777778 And Variance: 25.997214506172718
Mean: 9.916666666666666 And Variance: 20.098611111111072
Mean: 7.55 And Variance: 21.025277777777735
Mean: 0.12777777777777777 And Variance: 0.45033950617284135
Mean: 0.0 And Variance: 0.0
Mean: 0.42777777777777776 And Variance: 1.4892283950617307
Mean: 8.252777777777778 And Variance: 25.32777006172842
Mean: 8.802777777777777 And Variance: 29.230547839506198
Mean: 5.661111111111111 And Variance: 19.635154320987677
Mean: 10.891666666666667 And Variance: 21.53548611111111
Mean: 7.991666666666666 And Variance: 30.669374999999977
Mean: 0.3194444444444444 And Variance: 1.2285108024691433
Mean: 0.0 And Variance: 0.0
Mean: 0.044444444444444446 And Variance: 0.05358024691358013
Mean: 3.5833333333333335 And Variance: 14.015277777777778
Mean: 11.369444444444444 And Variance: 14.455177469135815
Mean: 14.119444444444444 And Variance: 9.888510802469138
Mean: 10.975 And Variance: 22.885486111111113
Mean: 3.2916666666666665 And Variance: 15.606597222222199
Mean: 0.075 And Variance: 0.18604166666666652
Mean: 7.5 And Variance: 2.25

In [123]:
num_channels = 64
input = Input(shape=(5000, num_channels))

branch_outputs = []
for i in range(num_channels):
    # Slicing the ith channel:
    out = Lambda(lambda x: x[:, i])(input)

    # Setting up your per-channel layers:
    out = Dense(64)(out)
    branch_outputs.append(out)

# Concatenating together the per-channel results:
out = Concatenate()(branch_outputs)

# Adding some further layers (replace or remove with your architecture):
out = Dense(10)(out)

In [124]:
# Building model:
model = Model(inputs=input, outputs=out)    
model.compile(optimizer=keras.optimizers.Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [125]:
# Generating dummy data:
import numpy as np
data = np.random.random((64, 5000, num_channels))
targets = np.random.randint(2, size=(64, 10))

In [126]:
# Training the model:
model.fit(data, targets, epochs=64, batch_size=32)

Epoch 1/64
2/2 [==============================] - 0s 10ms/step - loss: 35.1508 - accuracy: 0.0781
Epoch 2/64
2/2 [==============================] - 0s 13ms/step - loss: 39.0887 - accuracy: 0.2031
Epoch 3/64
2/2 [==============================] - 0s 16ms/step - loss: 38.8140 - accuracy: 0.2031
Epoch 4/64
2/2 [==============================] - 0s 16ms/step - loss: 38.7857 - accuracy: 0.2031
Epoch 5/64
2/2 [==============================] - 0s 12ms/step - loss: 38.5323 - accuracy: 0.2031
Epoch 6/64
2/2 [==============================] - 0s 20ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 7/64
2/2 [==============================] - 0s 12ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 8/64
2/2 [==============================] - 0s 16ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 9/64
2/2 [==============================] - 0s 10ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 10/64
2/2 [==============================] - 0s 11ms/step - loss: 38.7842 - accuracy: 0.2031
Epoch 11/64
2/2 [==============================] - 0s 10ms/step - loss: 38.7842 - accuracy: 0.2031
Epoch 12/64
2/2 [==============================] - 0s 17ms/step - loss: 38.7842 - accuracy: 0.2031
Epoch 13/64
2/2 [==============================] - 0s 15ms/step - loss: 38.7842 - accuracy: 0.2031
Epoch 14/64
2/2 [==============================] - 0s 11ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 15/64
2/2 [==============================] - 0s 12ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 16/64
2/2 [==============================] - 0s 18ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 17/64
2/2 [==============================] - 0s 20ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 18/64
2/2 [==============================] - 0s 12ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 19/64
2/2 [==============================] - 0s 10ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 20/64
2/2 [==============================] - 0s 14ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 21/64
2/2 [==============================] - 0s 9ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 22/64
2/2 [==============================] - 0s 10ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 23/64
2/2 [==============================] - 0s 13ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 24/64
2/2 [==============================] - 0s 12ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 25/64
2/2 [==============================] - 0s 13ms/step - loss: 38.2805 - accuracy: 0.2031
Epoch 26/64
2/2 [==============================] - 0s 10ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 27/64
2/2 [==============================] - 0s 12ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 28/64
2/2 [==============================] - 0s 13ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 29/64
2/2 [==============================] - 0s 14ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 30/64
2/2 [==============================] - 0s 17ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 31/64
2/2 [==============================] - 0s 12ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 32/64
2/2 [==============================] - 0s 13ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 33/64
2/2 [==============================] - 0s 19ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 34/64
2/2 [==============================] - 0s 13ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 35/64
2/2 [==============================] - 0s 12ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 36/64
2/2 [==============================] - 0s 15ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 37/64
2/2 [==============================] - 0s 18ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 38/64
2/2 [==============================] - 0s 18ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 39/64
2/2 [==============================] - 0s 16ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 40/64
2/2 [==============================] - 0s 12ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 41/64
2/2 [==============================] - 0s 18ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 42/64
2/2 [==============================] - 0s 14ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 43/64
2/2 [==============================] - 0s 15ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 44/64
2/2 [==============================] - 0s 13ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 45/64
2/2 [==============================] - 0s 12ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 46/64
2/2 [==============================] - 0s 15ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 47/64
2/2 [==============================] - 0s 17ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 48/64
2/2 [==============================] - 0s 15ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 49/64
2/2 [==============================] - 0s 13ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 50/64
2/2 [==============================] - 0s 10ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 51/64
2/2 [==============================] - 0s 11ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 52/64
2/2 [==============================] - 0s 11ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 53/64
2/2 [==============================] - 0s 13ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 54/64
2/2 [==============================] - 0s 11ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 55/64
2/2 [==============================] - 0s 15ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 56/64
2/2 [==============================] - 0s 11ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 57/64
2/2 [==============================] - 0s 10ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 58/64
2/2 [==============================] - 0s 14ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 59/64
2/2 [==============================] - 0s 15ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 60/64
2/2 [==============================] - 0s 11ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 61/64
2/2 [==============================] - 0s 12ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 62/64
2/2 [==============================] - 0s 11ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 63/64
2/2 [==============================] - 0s 6ms/step - loss: 38.0286 - accuracy: 0.2031
Epoch 64/64
2/2 [==============================] - 0s 9ms/step - loss: 38.0286 - accuracy: 0.2031

In [163]:
g1 = -0.5 * math.log(2 * np.pi)
g2 = math.log(np.var(df[column]))
#g3 = (((column) - (np.mean(df[column])))^2)/(2*((np.var(df[column]))^2))
gn = g1 - g2 
gn

-3.012123237900011

In [164]:
g1 = -0.5 * math.log(2 * np.pi)
g2 = math.log(np.var(df1[column]))
#g3 = (((column) - (np.mean(df[column])))^2)/(2*((np.var(df[column]))^2))
gn1 = g1 - g2 
gn1

-1.7298687494210014

In [165]:
if gn > gn1:
    print("training data (6) gives better performance.")
else:
    print("training data (9) gives better performance.")

training data (9) gives better performance.

In [181]:
dfn = df.assign(variance = df['6'])
dfn

,0,0.1,5,14,4,0.2,0.3,0.4,0.5,0.6,...,0.28,0.29,4.6,12.1,14.4,7,0.30,0.31,6.1,variance
0,0,0,0,10,12,0,0,0,0,0,...,0,0,1,11,14,12,1,0,6,2
1,0,0,2,14,10,0,0,0,0,1,...,0,0,1,12,14,12,4,0,6,6
2,0,0,2,13,5,0,0,0,0,0,...,0,0,4,15,12,9,1,0,6,2
3,0,0,2,13,6,0,0,0,0,0,...,0,0,2,12,14,12,4,0,6,0
4,0,0,1,12,11,0,0,0,0,0,...,0,0,2,14,15,12,3,0,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,0,0,0,8,13,10,5,0,0,0,...,0,0,0,14,15,2,0,0,9,0
195,0,0,0,3,10,13,12,4,0,0,...,0,0,0,1,15,1,0,0,9,0
196,0,0,0,4,10,13,12,0,0,0,...,0,0,0,2,11,0,0,0,9,0
197,0,0,6,14,16,9,0,0,0,5,...,0,0,8,14,16,13,1,0,9,0
198,0,0,2,13,16,7,0,0,0,0,...,0,0,2,12,16,16,4,0,9,0

In [176]:
dup = np.var(df1[column])
if dup == 0:
    df.drop_duplicates()
print(df)

     0  0.1  5  14   4  0.2  0.3  0.4  0.5  0.6  ...  0.27  0.28  0.29  4.6  \
0    0    0  0  10  12    0    0    0    0    0  ...     0     0     0    1
1    0    0  2  14  10    0    0    0    0    1  ...     0     0     0    1
2    0    0  2  13   5    0    0    0    0    0  ...     0     0     0    4
3    0    0  2  13   6    0    0    0    0    0  ...     0     0     0    2
4    0    0  1  12  11    0    0    0    0    0  ...     2     0     0    2
..  ..  ... ..  ..  ..  ...  ...  ...  ...  ...  ...   ...   ...   ...  ...
194  0    0  0   8  13   10    5    0    0    0  ...     0     0     0    0
195  0    0  0   3  10   13   12    4    0    0  ...     0     0     0    0
196  0    0  0   4  10   13   12    0    0    0  ...     0     0     0    0
197  0    0  6  14  16    9    0    0    0    5  ...     0     0     0    8
198  0    0  2  13  16    7    0    0    0    0  ...     0     0     0    2

     12.1  14.4   7  0.30  0.31  6.1
0      11    14  12     1     0    6
1      12    14  12     4     0    6
2      15    12   9     1     0    6
3      12    14  12     4     0    6
4      14    15  12     3     0    6
..    ...   ...  ..   ...   ...  ...
194    14    15   2     0     0    9
195     1    15   1     0     0    9
196     2    11   0     0     0    9
197    14    16  13     1     0    9
198    12    16  16     4     0    9

[199 rows x 65 columns]

In [184]:
indexNames = dfn[ dfn['variance'] == 0 ].index
dfn.drop(indexNames , inplace=True)
dfn

,0,0.1,5,14,4,0.2,0.3,0.4,0.5,0.6,...,0.28,0.29,4.6,12.1,14.4,7,0.30,0.31,6.1,variance
0,0,0,0,10,12,0,0,0,0,0,...,0,0,1,11,14,12,1,0,6,2
1,0,0,2,14,10,0,0,0,0,1,...,0,0,1,12,14,12,4,0,6,6
2,0,0,2,13,5,0,0,0,0,0,...,0,0,4,15,12,9,1,0,6,2
4,0,0,1,12,11,0,0,0,0,0,...,0,0,2,14,15,12,3,0,6,1
6,0,0,0,7,13,4,0,0,0,0,...,0,0,1,8,13,12,3,0,6,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,0,0,4,12,12,1,0,0,0,1,...,0,0,7,16,9,1,0,0,9,1
187,0,0,3,14,12,0,0,0,0,1,...,0,0,4,13,9,3,0,0,9,3
189,0,0,1,11,14,10,4,0,0,0,...,0,0,2,16,7,0,0,0,9,7
190,0,0,11,15,8,0,0,0,0,4,...,0,1,13,16,14,3,0,0,9,1
191,0,0,5,14,10,0,0,0,0,2,...,0,0,6,16,7,0,0,0,9,8

In [185]:
dfn1 = df1.assign(variance = df1['6'])
dfn1

,0,0.1,0.2,12,13,0.3,0.4,0.5,0.6,0.7,...,0.32,0.33,1,9,15.2,11.1,3.2,0.34,6,variance
0,0,0,0,8,15,1,0,0,0,0,...,0,0,0,7,15,16,11,0,6,6
1,0,0,1,13,14,3,0,0,0,0,...,0,0,3,12,15,14,7,0,6,6
2,0,0,0,5,14,2,0,0,0,0,...,0,0,0,5,16,15,3,0,6,6
3,0,0,0,10,13,1,0,0,0,1,...,0,0,0,7,15,15,5,0,6,6
4,0,0,0,9,10,0,0,0,0,0,...,0,0,0,6,12,14,9,0,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,0,0,7,16,9,8,2,0,0,5,...,0,0,7,15,14,7,0,0,9,9
356,0,0,5,14,11,8,0,0,0,4,...,0,0,7,15,12,5,0,0,9,9
357,0,0,4,14,15,6,0,0,0,5,...,0,0,4,13,15,9,0,0,9,9
358,0,0,4,10,13,6,0,0,0,1,...,0,0,2,14,15,9,0,0,9,9
359,0,0,2,10,7,0,0,0,0,0,...,0,0,5,12,16,12,0,0,9,9

In [186]:
indexNames = dfn1[ dfn1['variance'] == 0 ].index
dfn1.drop(indexNames , inplace=True)
dfn1

,0,0.1,0.2,12,13,0.3,0.4,0.5,0.6,0.7,...,0.32,0.33,1,9,15.2,11.1,3.2,0.34,6,variance
0,0,0,0,8,15,1,0,0,0,0,...,0,0,0,7,15,16,11,0,6,6
1,0,0,1,13,14,3,0,0,0,0,...,0,0,3,12,15,14,7,0,6,6
2,0,0,0,5,14,2,0,0,0,0,...,0,0,0,5,16,15,3,0,6,6
3,0,0,0,10,13,1,0,0,0,1,...,0,0,0,7,15,15,5,0,6,6
4,0,0,0,9,10,0,0,0,0,0,...,0,0,0,6,12,14,9,0,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,0,0,7,16,9,8,2,0,0,5,...,0,0,7,15,14,7,0,0,9,9
356,0,0,5,14,11,8,0,0,0,4,...,0,0,7,15,12,5,0,0,9,9
357,0,0,4,14,15,6,0,0,0,5,...,0,0,4,13,15,9,0,0,9,9
358,0,0,4,10,13,6,0,0,0,1,...,0,0,2,14,15,9,0,0,9,9
359,0,0,2,10,7,0,0,0,0,0,...,0,0,5,12,16,12,0,0,9,9

In [190]:
dfn1.head(10)

,0,0.1,0.2,12,13,0.3,0.4,0.5,0.6,0.7,...,0.32,0.33,1,9,15.2,11.1,3.2,0.34,6,variance
0,0,0,0,8,15,1,0,0,0,0,...,0,0,0,7,15,16,11,0,6,6
1,0,0,1,13,14,3,0,0,0,0,...,0,0,3,12,15,14,7,0,6,6
2,0,0,0,5,14,2,0,0,0,0,...,0,0,0,5,16,15,3,0,6,6
3,0,0,0,10,13,1,0,0,0,1,...,0,0,0,7,15,15,5,0,6,6
4,0,0,0,9,10,0,0,0,0,0,...,0,0,0,6,12,14,9,0,6,6
5,0,0,0,10,11,0,0,0,0,0,...,0,0,0,9,15,12,5,0,6,6
6,0,0,5,14,0,0,0,0,0,0,...,0,0,4,14,16,12,7,0,6,6
7,0,0,0,10,15,3,0,0,0,0,...,0,0,1,9,15,16,11,0,6,6
8,0,0,0,10,11,0,0,0,0,0,...,0,0,0,9,13,11,6,0,6,6
9,0,0,0,11,16,8,0,0,0,0,...,0,0,0,12,16,15,0,0,6,6

In [191]:
g1 = -0.5 * math.log(2 * np.pi)
g2 = math.log(np.var(dfn1[column]))
#g3 = (((column) - (np.mean(df[column])))^2)/(2*((np.var(df[column]))^2))
gn11 = g1 - g2 
gn11

-1.7298687494210014

In [192]:
if gn1 > gn11:
    print("training data (6) gives better performance.")
else:
    print("training data (9) gives better performance.")

training data (9) gives better performance.